### ISSUE TITLE
"MIME" as part of API name is unusual

### ISSUE THREAD

**Issue by foolip** [w3c/mediacapture-record#10]
[`MediaRecorder.canRecordMimeType()`](http://w3c.github.io/mediacapture-record/MediaRecorder.html#widl-MediaRecorder-canRecordMimeType-DOMString-DOMString-mimeType) is in contrast to the similar APIs [`HTMLMediaElement.canPlayType()`](https://html.spec.whatwg.org/#dom-navigator-canplaytype) and [`MediaSource.isTypeSupported()`](https://w3c.github.io/media-source/#widl-MediaSource-isTypeSupported-boolean-DOMString-type).

If there isn't already content that depends on it, it would also be nice to rename [`MediaRecorder.mimeType`](http://w3c.github.io/mediacapture-record/MediaRecorder.html#widl-MediaRecorder-mimeType).

**Comment by foolip** [comment]
Ping?

I would propose copying the signature of [`MediaSource`](https://w3c.github.io/media-source/#idl-def-MediaSource), which is `static boolean isTypeSupported (DOMString type)`.

Unlike for `HTMLMediaElement.canPlayType()`, there ought not be any uncertainty about whether or not a given type will result in some output. With media elements, `canPlayType("video/webm")` is supposed to return "maybe" because you don't know what the codecs will be, but when you ask to record using "video/webm", the implementation will either pick some suitable codecs that work with the container or it won't.

**Comment by yell0wd0g** [comment]
I agree with the signature part: isTypeSupported().

I disagree about answering "maybe" or "probably". A number of reasons might prevent the implementation from recording a given codec+container even if it's namely supported, for example resolution when a hardware encoder is in use, or excesive frame rate, and for that reason it can not be 100% sure until the video frames start arriving. Hence the answering will be "maybe" or "" most of the times.

**Comment by foolip** [comment]
What would be the distinction between "maybe" and "probably" The distinction for HTMLMediaElement is that "maybe" is returned if you just ask for a container and don't specify the codecs, because you don't know what the codecs will be. When encoding, that distinction doesn't make sense, because there are only two options:
1. A container on its own is never supported, i.e. specifying codecs is mandatory.
2. A container on its own implies some default codecs, and the return value would be the same as if the container and those default codecs had been requested.

It's still possible that encoding will fail for some reason, but the same is true of every case where HTMLMediaElement.prototype.canPlayType returns "maybe" or "probably".

**Comment by yell0wd0g** [comment]
So, regardless of HTMLMediaElement behaviour, the current wording in the spec is: 

> it must return "probably" if the user agent is confident that mimeType represents a type that it can record; and it must return "maybe" otherwise. Implementors are encouraged to return "maybe" unless the type can be confidently established as being supported or not.

And since the type can never be confidently established as being supported or not, because it depends on stream-specific information, such as pixel format (10bits per channel, for example, would hardly be supported), resolution and actual frame rate, all this boils down to `canRecordMimeType()` returning only "" or "maybe", but never "probably". But this is a different conversation, and IMHO very much UA dependent.

On the s/canRecordMimeType/isTypeSupported/, I think is a good idea, and better do it now than later; Gecko does not seem to implement any static method to query type support [1](or someone please help me find it), and I'm working on the adaptation in Cr [2].

[1] https://github.com/mozilla/gecko-dev/blob/master/dom/webidl/MediaRecorder.webidl
[2] https://codereview.chromium.org/1507183002/

**Comment by yell0wd0g** [comment]
And because of my comment before, I agree that it makes sense to return `true`/`false`, making note that a `true` does not guarantee that recording would happen.

So the linked patch takes over wording from [`MediaSource.isTypeSupported()`](https://w3c.github.io/media-source/#widl-MediaSource-isTypeSupported-boolean-DOMString-type) and returns a boolean.

On changing the attribute |MediaRecorder.mimeType|, I would file a separate issue, since it implies more modifications (Gecko and Blink implement it).

**Comment by yell0wd0g** [comment]
(Filed https://github.com/w3c/mediacapture-record/issues/35 to deal with renaming |mimeType|).

**Comment by yell0wd0g** [comment]
foolip@ I'm going to close this issue since the topic is addressed, and we have https://github.com/w3c/mediacapture-record/issues/35 to deal with the last bit of `mime` naming.

**Comment by foolip** [comment]
Thanks @miguelao!
