### ISSUE TITLE
Frame Rate

### ISSUE THREAD

**Issue by qhulamm** [w3c/mediacapture-record#148]
Is there any plan to implement frame rate control into the mediacapture API?  Currently it seems like it defaults to 30fps max.  It would be great to be able to record at lower or faster frame rates if the stream supports it.

**Comment by alvestrand** [comment]
The frame rate constraint is fully specified in the specification. For implementations, check with the browsers.

**Comment by alvestrand** [comment]
That is .. how to constrain the frame rate is fully specified in the "Media Capture And Streams" specification. The MediaRecorder is supposed to record at the rate the stream produces.

Please reopen issue if there's anything more unclear here.

**Comment by yell0wd0g** [comment]
Correct, Media Recorder records by definition as fast or as slow a rate as the feeding Media Stream Track(s) provide data (assuming it can cope). There's no provisions for buffering (pre-encoding) in it since it's a Real-Time recorder. The place to discuss frame rate tweaking is indeed the [Media Capture and Streams spec](https://w3c.github.io/mediacapture-main/).
