### ISSUE TITLE
What are the default bitrate attribute values?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-record#169]
The [videoBitsPerSecond](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-videobitspersecond) read-only attribute says *"The value of the Video encoding target bit rate that was passed to the Platform (potentially truncated, rounded, etc), or the calculated one if the user has specified bitsPerSecond."*

This does not say what to return If neither `videoBitsPerSecond` nor `bitsPerSecond` were passed. Ditto for [audioBitsPerSecond](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-audiobitspersecond).

Possible solutions:
 1. return `0`
 2. Make `audioBitsPerSecond` and `videoBitsPerSecond` attributes nullable.

**Comment by alvestrand** [comment]
My reading is that the encoder has to specify some target bitrate in order to operate at all, and this makes a means of reading what the implementation chose for you.

If it's not set, "return an UA-chosen value" seems correct to me. (Returning zero would indicate that you aren't going to produce anything unless a bitrate is specified, which seems silly.)

**Comment by jan-ivar** [comment]
@alvestrand Chrome returns `0`. From console:
```
> new MediaRecorder(new MediaStream()).audioBitsPerSecond
0

> new MediaRecorder(new MediaStream()).videoBitsPerSecond
0
```

**Comment by Pehrsons** [comment]
@yellowdoge your thoughts?

**Comment by jan-ivar** [comment]
I'd go with @alvestrand here.
