### ISSUE TITLE
Error member in an Event for runtime-errors is a bad idea

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-record#53]
...because the `Error`'s file, line number and stack will always be empty.

Not only is this wasteful, it fools people into thinking it _might_ have useful information that they better log or forward, taking the place of more useful information.

Here's an [example](https://jsfiddle.net/tmwLxjLy/) (yes I like promises, and yes the example is mediaRecorder,  but it has the same event):

``` js
var rec = new MediaRecorder(stream);
rec.start();
var stopped = new Promise((resolve, reject) => {
  rec.onstop = resolve;
  rec.onerror = event => reject(event.error));
});
```

`stopped` resolves when the recording ends, or rejects at the first runtime error, whichever happens first.

But when a `SecurityError` error later shows up in my console, there's no file or line number. In a larger program, this would suck.

If we replace `.error` with `.name` and `.message` then I know there's no deeper information to forward:

```
rec.onerror = event => reject(new DOMException(event.message, event.name));
```

And now the `SecurityError` points to this call site, which tells me it's a runtime error in `rec`.

I think this is a general problem with all runtime-error events.

**Comment by jan-ivar** [comment]
This issue is a clone of https://github.com/w3c/mediacapture-main/issues/337#issuecomment-209468754 (closed because mediacapture didn't need the error event in the end, but still relevant here).

**Comment by yell0wd0g** [comment]
Merging #31 into this issue.  

The Spec currently defines an [`ErrorEvent`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#errorevent) that just acts as a holder for a `DOMException`.

Gecko defines a RecordErrorEvent [1] that is used in MediaRecorder.cpp [2] by filling its name in NotifyError() to e.g. SecurityError, OutOfMemoryError or otherwise GenericError.  Chromium has no specific error.

Coalescing other conversations:
- using [`ErrorEvent`](https://html.spec.whatwg.org/multipage/webappapis.html#the-errorevent-interface) is not a good idea here because of the `filename`, `lineno` and `colno` that hints as to it being an error produced in a file;
- we still would  like to produce an Error Event interface with a `message` field;
- I personally think it'd be an overkill to define a sort-of `MediaRecorderErrorEvent` just to add a `DOMString` message field.

@jan-ivar, @foolip, what would you suggest we do?


[1] https://github.com/mozilla/gecko-dev/blob/master/dom/webidl/RecordErrorEvent.webidl
[2] https://github.com/mozilla/gecko-dev/blob/master/dom/media/MediaRecorder.cpp#L1385

**Comment by domenic** [comment]
So `ErrorEvent` as in the spec now is just incorrect since it collides with the existing `ErrorEvent` in HTML. Renaming it to `MediaRecorderErrorEvent` seems fine to me.

An implementation could definitely include a stack trace/filename/lineno/colno here, e.g. of the triggering script that called start. That's up to the implementation though.

**Comment by jan-ivar** [comment]
Wfm. Can we make the dict member `required` and the attribute non-nullable while we're at it?

**Comment by yell0wd0g** [comment]
Closing preventively, @domenic, @jan-ivar, please reopen if you see some fishy literature. Thanks!
