### ISSUE TITLE
Not clear how codecs works 

### ISSUE THREAD

**Issue by fluffy** [w3c/mediacapture-record#77]
Imagine I am on a browser that support vp8, opus, 264, g711 etc. Lets say I want to recording to be in vp8 with opus. How do I do that. Right now it does not look like I can do that. It seems that we need to be able to find out what audio codecs, video codecs, and containers are supported as well as say which combination to use.

**Comment by yell0wd0g** [comment]
1. MediaRecorder constructor accepts an optional [`MediaRecorderOptions`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#MediaRecorderOptions) with a  `mimeType` field that can be used to specify exactly that. There is a static method [`isTypeSupported`](https://w3c.github.io/mediacapture-record/MediaRecorder.html#dom-mediarecorder-istypesupported) that can be used to query if a given `mimeType` is supported by the UA. There are no examples in the Spec regarding that (or anything else, since there are no examples :smile:), so we might as well add them.
   
   This [StackOverflow question](http://stackoverflow.com/questions/35466078/specifying-codecs-with-mediarecorder/39735511) got answered that Cr implements `mimeType` support and FF doesn't. 
2. There is currently no way to query the formats supported by the UA, but there is issue #59 for that, and PR #65 in which I suggest you chime in to convince @martinthomson of the actual need for this functionality.
